// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCWrpDJHI8AHjdE6_g6yrEkPibm_9XDjs',
    appId: '1:340968443186:web:33b26d5f55018f21e4db2b',
    messagingSenderId: '340968443186',
    projectId: 'blogapp-3aed0',
    authDomain: 'blogapp-3aed0.firebaseapp.com',
    storageBucket: 'blogapp-3aed0.appspot.com',
    measurementId: 'G-TTD691SG20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDiEPevcF2m9FN36FdaCfG-OQwLc1sVps',
    appId: '1:340968443186:android:3155f26ad71c448de4db2b',
    messagingSenderId: '340968443186',
    projectId: 'blogapp-3aed0',
    storageBucket: 'blogapp-3aed0.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCWrpDJHI8AHjdE6_g6yrEkPibm_9XDjs',
    appId: '1:340968443186:web:9be655d13a64e14be4db2b',
    messagingSenderId: '340968443186',
    projectId: 'blogapp-3aed0',
    authDomain: 'blogapp-3aed0.firebaseapp.com',
    storageBucket: 'blogapp-3aed0.appspot.com',
    measurementId: 'G-TXB291HJCF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiM93ykQ0VHyh8TFdH-0puueyN4ySPtsY',
    appId: '1:340968443186:ios:686e5d92f90a9d45e4db2b',
    messagingSenderId: '340968443186',
    projectId: 'blogapp-3aed0',
    storageBucket: 'blogapp-3aed0.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

}